#include "atlas/resource/resource_registry.hpp"

#include <cstddef>
#include <filesystem>
#include <fstream>
#include <gtest/gtest.h>
#include <string>
#include <unordered_map>
#include <vector>

namespace atlas::resource {
namespace {

// Set by CMakeLists.txt to the absolute path of tests/atlas-resource/fixtures/
// - real packed blob files on disk, not a mocked filesystem, per CLAUDE.md's
// "test via a minimal test host, not by mocking behavior" rule. Generated by
// a one-off script matching atlas::rcc::pack_resource_blob's documented
// format exactly (independently of any reader, mirroring
// resource_id_test.cpp's "known reference values" precedent).
constexpr std::string_view fixtures_dir = ATLAS_RESOURCE_TEST_FIXTURES_DIR;

std::filesystem::path fixture(const std::string& name) {
    return std::filesystem::path{fixtures_dir} / name;
}

std::vector<std::byte> to_bytes(std::string_view text) {
    std::vector<std::byte> bytes;
    bytes.reserve(text.size());
    for (const char character : text) {
        bytes.push_back(static_cast<std::byte>(character));
    }
    return bytes;
}

ResourceRegistry make_registry() {
    return ResourceRegistry{{
        {"Mesh", fixture("mesh.blob")},
        {"Sound", fixture("sound.blob")},
        {"Broken", fixture("truncated_header.blob")},
    }};
}

TEST(ResourceRegistry, UnresolvedWhenTypeWasNeverRegistered) {
    const ResourceRegistry registry = make_registry();

    const Resolution resolution = registry.resolve("Texture", ResourceId::from_name("characters/hero/mesh"));

    EXPECT_EQ(resolution.status, ResolutionStatus::Unresolved);
    EXPECT_TRUE(resolution.bytes.empty());
}

TEST(ResourceRegistry, UnresolvedWhenIdAbsentFromALoadedBlob) {
    const ResourceRegistry registry = make_registry();

    const Resolution resolution =
        registry.resolve("Mesh", ResourceId::from_name("characters/hero/never-declared"));

    EXPECT_EQ(resolution.status, ResolutionStatus::Unresolved);
}

TEST(ResourceRegistry, UnresolvedForTheNullId) {
    const ResourceRegistry registry = make_registry();

    const Resolution resolution = registry.resolve("Mesh", ResourceId{});

    EXPECT_EQ(resolution.status, ResolutionStatus::Unresolved);
}

TEST(ResourceRegistry, ResolvedReturnsExactBytesFromTheBlob) {
    const ResourceRegistry registry = make_registry();

    const Resolution resolution = registry.resolve("Mesh", ResourceId::from_name("characters/hero/mesh"));

    ASSERT_EQ(resolution.status, ResolutionStatus::Resolved);
    EXPECT_EQ(resolution.bytes, to_bytes("MESHBLOBBYTES"));
}

TEST(ResourceRegistry, ResolutionFailedWhenTheBlobFileIsMissing) {
    ResourceRegistry registry{{{"Mesh", fixture("does-not-exist.blob")}}};

    const Resolution resolution = registry.resolve("Mesh", ResourceId::from_name("characters/hero/mesh"));

    EXPECT_EQ(resolution.status, ResolutionStatus::ResolutionFailed);
    EXPECT_TRUE(resolution.bytes.empty());
}

TEST(ResourceRegistry, ResolutionFailedWhenTheBlobHeaderIsTruncated) {
    const ResourceRegistry registry = make_registry();

    const Resolution resolution = registry.resolve("Broken", ResourceId::from_name("characters/hero/mesh"));

    EXPECT_EQ(resolution.status, ResolutionStatus::ResolutionFailed);
}

TEST(ResourceRegistry, ResolutionFailedWhenTheIndexIsTruncated) {
    ResourceRegistry registry{{{"Mesh", fixture("truncated_index.blob")}}};

    const Resolution resolution = registry.resolve("Mesh", ResourceId::from_name("characters/hero/mesh"));

    EXPECT_EQ(resolution.status, ResolutionStatus::ResolutionFailed);
}

TEST(ResourceRegistry, ResolutionFailedWhenAnEntryPointsPastTheEndOfTheData) {
    ResourceRegistry registry{{{"Mesh", fixture("out_of_bounds.blob")}}};

    const Resolution resolution = registry.resolve("Mesh", ResourceId::from_name("characters/hero/mesh"));

    EXPECT_EQ(resolution.status, ResolutionStatus::ResolutionFailed);
}

TEST(ResourceRegistry, EntriesPartitionByTypeWithNoCrossContamination) {
    const ResourceRegistry registry = make_registry();

    // "characters/hero/theme" only exists in sound.blob - asking the Mesh
    // partition for it must not find it just because the id exists
    // somewhere in the registry.
    const Resolution as_mesh = registry.resolve("Mesh", ResourceId::from_name("characters/hero/theme"));
    const Resolution as_sound = registry.resolve("Sound", ResourceId::from_name("characters/hero/theme"));

    EXPECT_EQ(as_mesh.status, ResolutionStatus::Unresolved);
    EXPECT_EQ(as_sound.status, ResolutionStatus::Resolved);
}

TEST(ResourceRegistry, RepeatedResolveCallsProduceBitIdenticalOutput) {
    const ResourceRegistry registry = make_registry();
    const auto id = ResourceId::from_name("characters/hero/mesh");

    const Resolution first = registry.resolve("Mesh", id);
    const Resolution second = registry.resolve("Mesh", id);

    EXPECT_EQ(first.status, second.status);
    EXPECT_EQ(first.bytes, second.bytes);
}

TEST(ResourceRegistry, ResolveNeverTouchesTheFilesystemAfterConstruction) {
    // Copy mesh.blob to a scratch path, construct against the copy, then
    // delete the copy - resolve() must still succeed, proving every blob is
    // fully resident in memory after construction rather than re-read per
    // call.
    const std::filesystem::path scratch = fixture("scratch_mesh.blob");
    std::filesystem::copy_file(
        fixture("mesh.blob"), scratch, std::filesystem::copy_options::overwrite_existing);

    ResourceRegistry registry{{{"Mesh", scratch}}};
    std::filesystem::remove(scratch);

    const Resolution resolution = registry.resolve("Mesh", ResourceId::from_name("characters/hero/mesh"));

    ASSERT_EQ(resolution.status, ResolutionStatus::Resolved);
    EXPECT_EQ(resolution.bytes, to_bytes("MESHBLOBBYTES"));
}

} // namespace
} // namespace atlas::resource
