add_subdirectory(atlas-core)
add_subdirectory(atlas-entity)
add_subdirectory(atlas-contracts)
add_subdirectory(atlas-stage)
add_subdirectory(atlas-resource)
add_subdirectory(atlas-serialization)
add_subdirectory(atlas-reflection)
add_subdirectory(atlas-request)
add_subdirectory(atlas-scheduler)
add_subdirectory(atlas-replication)
add_subdirectory(atlas-runtime)
add_subdirectory(atlas-input)
