# Script-mode helper (invoked via `cmake -P ... -DINPUT_FILE=... -DOUTPUT_FILE=... -DCPP_NAME=...`)
# that embeds a text file's exact bytes as a `constexpr std::string_view` in
# a generated header. This lets template files live as separate, directly
# editable files (tools/atlas-cgen/templates/*.tmpl) without the consuming
# binary needing to locate them on disk at runtime - it's invoked from an
# add_custom_command with the template file as a DEPENDS, so it re-runs (and
# whatever links the generated header rebuilds) whenever the .tmpl changes,
# same as any other generated build input.
#
# Embedding via a C++ raw string literal means no escaping is needed for the
# template's own quotes/backslashes. Two constraints this relies on: the
# delimiter must be <=16 characters (a hard C++ raw-string-literal limit -
# ATLAS_TEMPLATE is 14), and no template file's content may contain the
# exact sequence ")ATLAS_TEMPLATE\"" (true today; would need a different
# delimiter if that ever changed).
if(NOT DEFINED INPUT_FILE OR NOT DEFINED OUTPUT_FILE OR NOT DEFINED CPP_NAME)
  message(FATAL_ERROR "EmbedTextFile.cmake requires -DINPUT_FILE=, -DOUTPUT_FILE=, -DCPP_NAME=")
endif()

file(READ "${INPUT_FILE}" embed_text_file_content)

file(
  WRITE "${OUTPUT_FILE}"
  "// GENERATED by EmbedTextFile.cmake from ${INPUT_FILE} — do not hand-edit.\n"
  "#pragma once\n\n"
  "#include <string_view>\n\n"
  "namespace atlas::cgen::templates {\n\n"
  "inline constexpr std::string_view ${CPP_NAME} = R\"ATLAS_TEMPLATE(${embed_text_file_content})ATLAS_TEMPLATE\";\n\n"
  "}  // namespace atlas::cgen::templates\n")
