# Script-mode helper (invoked via `cmake -P ... -DINPUT_FILE=... -DOUTPUT_FILE=...
# -DCPP_NAME=... -DCPP_NAMESPACE=...`) that embeds a shader source file's
# exact bytes as a `constexpr std::string_view` in a generated header - the
# same technique tools/atlas-cgen/cmake/scripts/EmbedTextFile.cmake already
# uses for its own template files, reimplemented here (parameterized by
# namespace) rather than shared, so this library's shader sources stay
# independent of atlas-cgen's own tooling.
#
# Compiling HLSL at runtime (see sdl3_shader_pipeline.cpp) still needs the
# HLSL *source text* available inside the running binary; embedding it here
# means callers (including this library's own tests) never need to locate
# libraries/atlas-render/shaders/*.hlsl on disk at runtime - no working-directory
# or install-path assumption, matching every other checked-in-but-baked-in-at-
# build-time asset in this project (tools/atlas-cgen's own templates).
#
# Two constraints this relies on (identical to EmbedTextFile.cmake): the raw
# string delimiter must be <=16 characters (ATLAS_SHADER is 12), and no
# shader file's content may contain the exact sequence ")ATLAS_SHADER\"" -
# true today for both checked-in .hlsl files.
if(NOT DEFINED INPUT_FILE
   OR NOT DEFINED OUTPUT_FILE
   OR NOT DEFINED CPP_NAME
   OR NOT DEFINED CPP_NAMESPACE)
  message(FATAL_ERROR "EmbedShaderSource.cmake requires -DINPUT_FILE=, -DOUTPUT_FILE=, -DCPP_NAME=, "
                       "-DCPP_NAMESPACE=")
endif()

file(READ "${INPUT_FILE}" embed_shader_source_content)

file(
  WRITE "${OUTPUT_FILE}"
  "// GENERATED by EmbedShaderSource.cmake from ${INPUT_FILE} — do not hand-edit.\n"
  "#pragma once\n\n"
  "#include <string_view>\n\n"
  "namespace ${CPP_NAMESPACE} {\n\n"
  "inline constexpr std::string_view ${CPP_NAME} = R\"ATLAS_SHADER(${embed_shader_source_content})ATLAS_SHADER\";\n\n"
  "} // namespace ${CPP_NAMESPACE}\n")
